#cloud-config
users:
  - name: database
    # don't commit me if I have a value...
    ssh-authorized-keys:
      - foo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
runcmd:
  - |
    sudo apt-get -y install postgresql \
    && sudo apt-get install -y iputils-ping \
    && sudo apt-get install -y dnsutils \
    && sudo apt-get install -y netcat
  - sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '0.0.0.0'/g" /etc/postgresql/12/main/postgresql.conf
  - sudo service postgresql restart
  - curl -fsSL https://tailscale.com/install.sh | sh
